config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'signup', to: 'users#new', as: 'signup'
  resources :users, except: [:show, :index, :new]
  get 'login', to: 'users#login', as: 'login'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates_confirmation_of :password
  validates :password_confirmation, :presence =>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  # before_action :login_required

  # #This method checks if we have a user signed in
  # def login_required
  #   if !logged_in?
  #         redirect_to login_path, :notice => “Log in to edit or delete your post”
  #   end
  # end

  # def logged_in?
  #   !!current_user
  # end

  # helper_method :logged_in?

  # #This method gives us details about our user
  # def current_user
  #   if session[:user_id]
  #     @current_user = User.find(session[:user_id])
  #     @current_user
  #   else
  #     false
  #   end
  # end

  # helper_method :current_user

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # skip_before_action :login_required, :only => [:index, :show]
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end
  
  def show
  end
  
  def new
    @article = Article.new
  end
  
  def create
    article = Article.create(build_article)
    redirect_to articles_path
  end
  
  def edit
  end
  
  
  def update
    @article.update(build_article)
    redirect_to article_path
  end
  
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def build_article
    params.require(:article).permit(:title, :content)
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  def login
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      # redirect_to @user, notice: 'User was successfully created.'
      session[:user_id] = @user.id   
      redirect_to articles_url, notice: 'User successfully created.' 
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(article) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="card my-3 border-0">
    <div class="card-body">
      <h3 class="inline-block card-title border-bottom py-2"><%= link_to article.title, article_path(article), class: "article-title" %></h3>
      <p class="card-text"><%= article.content %></p>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="card my-3 border-0">
  <div class="card-body">
    <h3 class="inline-block card-title border-bottom py-2">
      <%= @article.title %>
      <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_article_path %>
      <%= link_to '<i class="fas fa-trash"></i>'.html_safe, article_path, method: "delete", data: { confirm: "Do you want to delete this article?" } %>
    </h3>
    <p class="card-text"><%= @article.content %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-light bg-light justify-content-between px-5">
      <%= link_to '<h3 class="inline-block">Article</h3>'.html_safe, articles_path %>
      <%= link_to "create a article", new_article_path %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/login.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "log in" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>